# Challenge 1

In this challenge you will be working on **pokemons**. You will answer a series of questions in order to practice dataframe calculation, aggregation, and transformation.

![Pokemon](pokemon.jpg)

Follow the instructions below and enter your code.

### Import all required libraries

In [1]:
# import libraries
import pandas as pd
import numpy as np
import statistics as stat
import re
from numpy import nan

### Import data set

Import data set `Pokemon.csv` from the `your-code` directory of this lab. Read the data into a dataframe called `pokemon`.

*Data set attributed to [Alberto Barradas](https://www.kaggle.com/abcsds/pokemon/)*

In [2]:
# import data set
pokemon = pd.read_csv('C:/Users/rsher/lab-df-calculation-and-transformation/your-code/Pokemon.csv')

### Print first 10 rows of `pokemon`

In [3]:
# enter your code here
pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

When you look at a data set, you often wonder what each column means. Some open-source data sets provide descriptions of the data set. In many cases, data descriptions are extremely useful for data analysts to perform work efficiently and successfully.

For the `Pokemon.csv` data set, fortunately, the owner provided descriptions which you can see [here](https://www.kaggle.com/abcsds/pokemon/home). For your convenience, we are including the descriptions below. Read the descriptions and understand what each column means. This knowledge is helpful in your work with the data.

| Column | Description |
| --- | --- |
| # | ID for each pokemon |
| Name | Name of each pokemon |
| Type 1 | Each pokemon has a type, this determines weakness/resistance to attacks |
| Type 2 | Some pokemon are dual type and have 2 |
| Total | A general guide to how strong a pokemon is |
| HP | Hit points, or health, defines how much damage a pokemon can withstand before fainting |
| Attack | The base modifier for normal attacks (eg. Scratch, Punch) |
| Defense | The base damage resistance against normal attacks |
| SP Atk | Special attack, the base modifier for special attacks (e.g. fire blast, bubble beam) |
| SP Def | The base damage resistance against special attacks |
| Speed | Determines which pokemon attacks first each round |
| Generation | Number of generation |
| Legendary | True if Legendary Pokemon False if not |

### Obtain the distinct values across `Type 1` and `Type 2`

Exctract all the values in `Type 1` and `Type 2`. Then create an array containing the distinct values across both fields.

In [4]:
# enter your code here
pok_array = np.array(pokemon['Type 1'], pokemon['Type 2'])
pok_array

array(['Grass', 'Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Fire',
       'Fire', 'Water', 'Water', 'Water', 'Water', 'Bug', 'Bug', 'Bug',
       'Bug', 'Bug', 'Bug', 'Bug', 'Normal', 'Normal', 'Normal', 'Normal',
       'Normal', 'Normal', 'Normal', 'Normal', 'Poison', 'Poison',
       'Electric', 'Electric', 'Ground', 'Ground', 'Poison', 'Poison',
       'Poison', 'Poison', 'Poison', 'Poison', 'Fairy', 'Fairy', 'Fire',
       'Fire', 'Normal', 'Normal', 'Poison', 'Poison', 'Grass', 'Grass',
       'Grass', 'Bug', 'Bug', 'Bug', 'Bug', 'Ground', 'Ground', 'Normal',
       'Normal', 'Water', 'Water', 'Fighting', 'Fighting', 'Fire', 'Fire',
       'Water', 'Water', 'Water', 'Psychic', 'Psychic', 'Psychic',
       'Psychic', 'Fighting', 'Fighting', 'Fighting', 'Grass', 'Grass',
       'Grass', 'Water', 'Water', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire',
       'Water', 'Water', 'Water', 'Electric', 'Electric', 'Normal',
       'Normal', 'Normal', 'Water', 'Water', 'Poison', 'Poison', 'Water',
       'Water', 'Ghost', 'Ghost', 'Ghost', 'Ghost', 'Rock', 'Psychic',
       'Psychic', 'Water', 'Water', 'Electric', 'Electric', 'Grass',
       'Grass', 'Ground', 'Ground', 'Fighting', 'Fighting', 'Normal',
       'Poison', 'Poison', 'Ground', 'Ground', 'Normal', 'Grass',
       'Normal', 'Normal', 'Water', 'Water', 'Water', 'Water', 'Water',
       'Water', 'Psychic', 'Bug', 'Ice', 'Electric', 'Fire', 'Bug', 'Bug',
       'Normal', 'Water', 'Water', 'Water', 'Water', 'Normal', 'Normal',
       'Water', 'Electric', 'Fire', 'Normal', 'Rock', 'Rock', 'Rock',
       'Rock', 'Rock', 'Rock', 'Normal', 'Ice', 'Electric', 'Fire',
       'Dragon', 'Dragon', 'Dragon', 'Psychic', 'Psychic', 'Psychic',
       'Psychic', 'Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire',
       'Water', 'Water', 'Water', 'Normal', 'Normal', 'Normal', 'Normal',
       'Bug', 'Bug', 'Bug', 'Bug', 'Poison', 'Water', 'Water', 'Electric',
       'Fairy', 'Normal', 'Fairy', 'Fairy', 'Psychic', 'Psychic',
       'Electric', 'Electric', 'Electric', 'Electric', 'Grass', 'Water',
       'Water', 'Rock', 'Water', 'Grass', 'Grass', 'Grass', 'Normal',
       'Grass', 'Grass', 'Bug', 'Water', 'Water', 'Psychic', 'Dark',
       'Dark', 'Water', 'Ghost', 'Psychic', 'Psychic', 'Normal', 'Bug',
       'Bug', 'Normal', 'Ground', 'Steel', 'Steel', 'Fairy', 'Fairy',
       'Water', 'Bug', 'Bug', 'Bug', 'Bug', 'Bug', 'Dark', 'Normal',
       'Normal', 'Fire', 'Fire', 'Ice', 'Ice', 'Water', 'Water', 'Water',
       'Ice', 'Water', 'Steel', 'Dark', 'Dark', 'Dark', 'Water', 'Ground',
       'Ground', 'Normal', 'Normal', 'Normal', 'Fighting', 'Fighting',
       'Ice', 'Electric', 'Fire', 'Normal', 'Normal', 'Electric', 'Fire',
       'Water', 'Rock', 'Rock', 'Rock', 'Rock', 'Psychic', 'Fire',
       'Psychic', 'Grass', 'Grass', 'Grass', 'Grass', 'Fire', 'Fire',
       'Fire', 'Fire', 'Water', 'Water', 'Water', 'Water', 'Dark', 'Dark',
       'Normal', 'Normal', 'Bug', 'Bug', 'Bug', 'Bug', 'Bug', 'Water',
       'Water', 'Water', 'Grass', 'Grass', 'Grass', 'Normal', 'Normal',
       'Water', 'Water', 'Psychic', 'Psychic', 'Psychic', 'Psychic',
       'Bug', 'Bug', 'Grass', 'Grass', 'Normal', 'Normal', 'Normal',
       'Bug', 'Bug', 'Bug', 'Normal', 'Normal', 'Normal', 'Fighting',
       'Fighting', 'Normal', 'Rock', 'Normal', 'Normal', 'Dark', 'Dark',
       'Steel', 'Steel', 'Steel', 'Steel', 'Steel', 'Steel', 'Fighting',
       'Fighting', 'Fighting', 'Electric', 'Electric', 'Electric',
       'Electric', 'Electric', 'Bug', 'Bug', 'Grass', 'Poison', 'Poison',
       'Water', 'Water', 'Water', 'Water', 'Water', 'Fire', 'Fire',
       'Fire', 'Fire', 'Psychic', 'Psychic', 'Normal', 'Ground', 'Ground',
       'Ground', 'Grass', 'Grass', 'Normal', 'Dragon', 'Dragon', 'Normal',
       'Poison', 'Rock', 'Rock', 'Water', 'Water', 'Water', 'Water',
       'Ground', 'Ground', 'Rock', 'Rock', 'Rock', 'Rock', 'Water',
       'Water', 'Normal', 'Normal', 'Ghost', 'Ghost', 'Ghost', 'Ghost',
       'Ghost', 'Grass', 'Psychic', 'Dark', 'Dark', 'Psychic', 'Ice',
       'Ice', 'Ice', 'Ice', 'Ice', 'Ice', 'Water', 'Water', 'Water',
       'Water', 'Water', 'Dragon', 'Dragon', 'Dragon', 'Dragon', 'Steel',
       'Steel', 'Steel', 'Steel', 'Rock', 'Ice', 'Steel', 'Dragon',
       'Dragon', 'Dragon', 'Dragon', 'Water', 'Water', 'Ground', 'Ground',
       'Dragon', 'Dragon', 'Steel', 'Psychic', 'Psychic', 'Psychic',
       'Psychic', 'Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire',
       'Water', 'Water', 'Water', 'Normal', 'Normal', 'Normal', 'Normal',
       'Normal', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric',
       'Grass', 'Grass', 'Rock', 'Rock', 'Rock', 'Rock', 'Bug', 'Bug',
       'Bug', 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Water', 'Water',
       'Grass', 'Grass', 'Water', 'Water', 'Normal', 'Ghost', 'Ghost',
       'Normal', 'Normal', 'Normal', 'Ghost', 'Dark', 'Normal', 'Normal',
       'Psychic', 'Poison', 'Poison', 'Steel', 'Steel', 'Rock', 'Psychic',
       'Normal', 'Normal', 'Ghost', 'Dragon', 'Dragon', 'Dragon',
       'Dragon', 'Normal', 'Fighting', 'Fighting', 'Fighting', 'Ground',
       'Ground', 'Poison', 'Poison', 'Poison', 'Poison', 'Grass', 'Water',
       'Water', 'Water', 'Grass', 'Grass', 'Grass', 'Dark', 'Electric',
       'Normal', 'Ground', 'Grass', 'Electric', 'Fire', 'Fairy', 'Bug',
       'Grass', 'Ice', 'Ground', 'Ice', 'Normal', 'Psychic', 'Psychic',
       'Rock', 'Ghost', 'Ice', 'Electric', 'Electric', 'Electric',
       'Electric', 'Electric', 'Electric', 'Psychic', 'Psychic',
       'Psychic', 'Steel', 'Water', 'Fire', 'Normal', 'Ghost', 'Ghost',
       'Psychic', 'Water', 'Water', 'Dark', 'Grass', 'Grass', 'Normal',
       'Psychic', 'Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire',
       'Water', 'Water', 'Water', 'Normal', 'Normal', 'Normal', 'Normal',
       'Normal', 'Dark', 'Dark', 'Grass', 'Grass', 'Fire', 'Fire',
       'Water', 'Water', 'Psychic', 'Psychic', 'Normal', 'Normal',
       'Normal', 'Electric', 'Electric', 'Rock', 'Rock', 'Rock',
       'Psychic', 'Psychic', 'Ground', 'Ground', 'Normal', 'Normal',
       'Fighting', 'Fighting', 'Fighting', 'Water', 'Water', 'Water',
       'Fighting', 'Fighting', 'Bug', 'Bug', 'Bug', 'Bug', 'Bug', 'Bug',
       'Grass', 'Grass', 'Grass', 'Grass', 'Water', 'Ground', 'Ground',
       'Ground', 'Fire', 'Fire', 'Fire', 'Grass', 'Bug', 'Bug', 'Dark',
       'Dark', 'Psychic', 'Ghost', 'Ghost', 'Water', 'Water', 'Rock',
       'Rock', 'Poison', 'Poison', 'Dark', 'Dark', 'Normal', 'Normal',
       'Psychic', 'Psychic', 'Psychic', 'Psychic', 'Psychic', 'Psychic',
       'Water', 'Water', 'Ice', 'Ice', 'Ice', 'Normal', 'Normal',
       'Electric', 'Bug', 'Bug', 'Grass', 'Grass', 'Water', 'Water',
       'Water', 'Bug', 'Bug', 'Grass', 'Grass', 'Steel', 'Steel', 'Steel',
       'Electric', 'Electric', 'Electric', 'Psychic', 'Psychic', 'Ghost',
       'Ghost', 'Ghost', 'Dragon', 'Dragon', 'Dragon', 'Ice', 'Ice',
       'Ice', 'Bug', 'Bug', 'Ground', 'Fighting', 'Fighting', 'Dragon',
       'Ground', 'Ground', 'Dark', 'Dark', 'Normal', 'Normal', 'Normal',
       'Dark', 'Dark', 'Fire', 'Bug', 'Dark', 'Dark', 'Dark', 'Bug',
       'Bug', 'Steel', 'Rock', 'Grass', 'Flying', 'Flying', 'Electric',
       'Electric', 'Dragon', 'Dragon', 'Ground', 'Ground', 'Dragon',
       'Dragon', 'Dragon', 'Water', 'Water', 'Normal', 'Normal', 'Bug',
       'Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water',
       'Water', 'Water', 'Normal', 'Normal', 'Normal', 'Fire', 'Fire',
       'Bug', 'Bug', 'Bug', 'Fire', 'Fire', 'Fairy', 'Fairy', 'Fairy',
       'Grass', 'Grass', 'Fighting', 'Fighting', 'Normal', 'Psychic',
       'Psychic', 'Psychic', 'Steel', 'Steel', 'Steel', 'Steel', 'Fairy',
       'Fairy', 'Fairy', 'Fairy', 'Dark', 'Dark', 'Rock', 'Rock',
       'Poison', 'Poison', 'Water', 'Water', 'Electric', 'Electric',
       'Rock', 'Rock', 'Rock', 'Rock', 'Fairy', 'Fighting', 'Electric',
       'Rock', 'Dragon', 'Dragon', 'Dragon', 'Steel', 'Ghost', 'Ghost',
       'Ghost', 'Ghost', 'Ghost', 'Ghost', 'Ghost', 'Ghost', 'Ghost',
       'Ghost', 'Ice', 'Ice', 'Flying', 'Flying', 'Fairy', 'Dark',
       'Dragon', 'Rock', 'Rock', 'Psychic', 'Psychic', 'Fire'],
      dtype=object)

### Cleanup `Name` that contain "Mega"

If you have checked out the pokemon names carefully enough, you should have found there are junk texts in the pokemon names which contain "Mega". We want to clean up the pokemon names. For instance, "VenusaurMega Venusaur" should be "Mega Venusaur", and "CharizardMega Charizard X" should be "Mega Charizard X".

In [5]:
# enter your code here
pokemon['Name'] = pokemon['Name'].replace('\w+Mega','Mega',regex=True)

# test transformed data
pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,Mega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,Mega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

### Create a new column called `A/D Ratio` whose value equals to `Attack` devided by `Defense`

For instance, if a pokemon has the Attack score 49 and Defense score 49, the corresponding `A/D Ratio` is 49/49=1.

In [6]:
# enter your code here
pokemon['A/D_Ratio'] = pokemon['Attack'] / pokemon['Defense']
pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D_Ratio
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.209302

### Identify the pokemon with the highest `A/D Ratio`

In [7]:
# enter your code here
pokemon['A/D_Ratio'].max()

9.0

### Identify the pokemon with the lowest A/D Ratio

In [8]:
# enter your code here
pokemon['A/D_Ratio'].min()

0.043478260869565216

### Create a new column called `Combo Type` whose value combines `Type 1` and `Type 2`.

Rules:

* If both `Type 1` and `Type 2` have valid values, the `Combo Type` value should contain both values in the form of `<Type 1> <Type 2>`. For example, if `Type 1` value is `Grass` and `Type 2` value is `Poison`, `Combo Type` will be `Grass-Poison`.

* If `Type 1` has valid value but `Type 2` is not, `Combo Type` will be the same as `Type 1`. For example, if `Type 1` is `Fire` whereas `Type 2` is `NaN`, `Combo Type` will be `Fire`.

In [9]:
# enter your code here
pokemon['Type 2'].fillna("No", inplace = True)
pokemon['Combo Type'] = np.where(pokemon['Type 2'] != "No", 
                                 pokemon['Type 1'] + "-" + pokemon['Type 2'], pokemon['Type 1'])
pokemon['Combo Type'].head(20)

0     Grass-Poison
1     Grass-Poison
2     Grass-Poison
3     Grass-Poison
4             Fire
5             Fire
6      Fire-Flying
7      Fire-Dragon
8      Fire-Flying
9            Water
10           Water
11           Water
12           Water
13             Bug
14             Bug
15      Bug-Flying
16      Bug-Poison
17      Bug-Poison
18      Bug-Poison
19      Bug-Poison
Name: Combo Type, dtype: object

### Identify the pokemons whose `A/D Ratio` are among the top 5

In [10]:
# enter your code here
top5ratio = pokemon.sort_values(by=['A/D_Ratio'], ascending=False)
top5ratio.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D_Ratio,Combo Type
429,386,DeoxysAttack Forme,Psychic,No,600,50,180,20,180,20,150,3,True,9.000,Psychic
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.500,Water-Dark
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750,Bug-Poison
453,408,Cranidos,Rock,No,350,67,125,40,30,30,58,4,False,3.125,Rock
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,3.000,Water-Dark

### For the 5 pokemons printed above, aggregate `Combo Type` and use a list to store the unique values.

Your end product is a list containing the distinct `Combo Type` values of the 5 pokemons with the highest `A/D Ratio`.

In [11]:
# enter your code here
list_combo = top5ratio['Combo Type'].head(5)
list_combo

429       Psychic
347    Water-Dark
19     Bug-Poison
453          Rock
348    Water-Dark
Name: Combo Type, dtype: object

# For each of the `Combo Type` values obtained from the previous question, calculate the mean scores of all numeric fields across all pokemons.

Your output should look like below:

![Aggregate](aggregated-mean.png)

In [60]:
# enter your code here
ag_ct = pokemon.groupby('Combo Type')[pokemon.columns].mean().loc[list_combo]
ag_ct

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D_Ratio
Combo Type,,,,,,,,,,,
Psychic,381.973684,464.552632,72.552632,64.947368,67.236842,98.552632,82.394737,78.868421,3.342105,0.236842,1.164196
Water-Dark,347.666667,493.833333,69.166667,120.000000,65.166667,88.833333,63.500000,87.166667,3.166667,0.000000,2.291949
Bug-Poison,199.166667,347.916667,53.750000,68.333333,58.083333,42.500000,59.333333,65.916667,2.333333,0.000000,1.315989
Rock,410.111111,409.444444,67.111111,103.333333,107.222222,40.555556,58.333333,32.888889,3.888889,0.111111,1.260091
Water-Dark,347.666667,493.833333,69.166667,120.000000,65.166667,88.833333,63.500000,87.166667,3.166667,0.000000,2.291949